### ISSUE TITLE
feature: arbitrary protocol in link

### ISSUE THREAD

**Issue by majidaldo** [twinkle-labs/twinkle-notes#2]
...doesn't have to be http. Could be application links too.

**Comment by litchie** [comment]
What kind of format do you expect?

**Comment by majidaldo** [comment]
ftp as far as internet protocols. application protocols could be like skype or zoom links.

**Comment by litchie** [comment]
I think we can do that.

**Comment by majidaldo** [comment]
> I think we can do that.

nice! this leads to better integration with specialized applications like reference managers in my use case: zotero:/some/api

**Comment by majidaldo** [comment]
slllight issue here: file: // doesn't work. i think it maybe looking for local references [file: ...]. also had to access the app via web browser for the link to work.
