### ISSUE TITLE
use markdown

### ISSUE THREAD

**Issue by majidaldo** [twinkle-labs/twinkle-notes#6]
Looking at note-parser.js, I'm not sure why you decided to create your own markup. Besides the markup, it gets you html integration.

(for example, creating bullet lists was not documented. you have to start a line with -. looks like nested list is not supported.)

**Comment by litchie** [comment]
We wanted to, but it's not enough for our use case anyway. The main difference is to support math between $$ and special references in a pair of brackets. If html content is needed, maybe we should support open HTML in an iframe.
 I think it's pretty much a standard way to create a bullet list with -.
The principle of Twinkle Notes is to keep each note short, and when nested lists are needed, it's a sign to break up your notes. You can create sub branches for a note.
